version: '3'

services:
  hmi:
    build:
      context: ./hmi/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"      
      - "5001:5001"

  mqtt:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt
    ports:
      - "1883:1883" 
      - "9001:9001" 
    volumes:
      - ./broker/mqtt/config:/mosquitto/config:rw
    restart: unless-stopped

volumes:
  config:
